kind: Service
apiVersion: v1
metadata:
  name: ngx-svc
spec:
 ports:
 - name: web
   port: 80
 selector:
   app: ngx-app
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ngx-app
  labels:
    app: ngx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx-pod
  template:
    metadata:
      labels:
        app: ngx-pod
    spec:
      containers:
      - name: web-server
        image: registry.cn-hangzhou.aliyuncs.com/google_images_containers/nginx-alpine:v1.15.5-3.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
