apiVersion: v1
kind: Service
metadata:
  name: appsvc
spec:
  type: NodePort
  ports:
  - port: 5002
  selector:
    app: appsvc
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: appsvc
spec:
  selector:
    matchLabels:
      app: appsvc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: appsvc
    spec:
      containers:
      - image: harbor.nantong.com:9001/dev/app:latest
        name: appsvc
        env:
        - name: version
          value: '1'
        ports:
        - containerPort: 5000
          name: version