apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv1
  labels:
    app: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/nfs/mysql
    server: 172.20.20.74